### ISSUE TITLE
Runtime error in latest python 3.10.10, pytorch version 2.0.0

### ISSUE THREAD

**Issue by sGourapura** [bregaldo/pywph#5]
Hi,

I am attempting to run your ipynb on a fresh install of python and pytorch,  and am getting the below runtime error during the gradient and the optimization calculations.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[44], line 10
      8 y_coeffs_chunk, indices = wph_op(y_torch, i, ret_indices=True)
      9 loss_chunk = (torch.absolute(y_coeffs_chunk - x_coeffs[indices]) ** 2).sum()
---> 10 loss_chunk.backward(retain_graph=True)
     11 coeffs.append(y_coeffs_chunk.detach().cpu())
     12 del y_coeffs_chunk, loss_chunk # To free GPU memory

File [~/anaconda3/lib/python3.10/site-packages/torch/_tensor.py:487](https://file+.vscode-resource.vscode-cdn.net/Users/suren/Desktop/Research/generative_models/pywph/examples/~/anaconda3/lib/python3.10/site-packages/torch/_tensor.py:487), in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    477 if has_torch_function_unary(self):
    478     return handle_torch_function(
    479         Tensor.backward,
    480         (self,),
   (...)
    485         inputs=inputs,
    486     )
--> 487 torch.autograd.backward(
    488     self, gradient, retain_graph, create_graph, inputs=inputs
    489 )

File [~/anaconda3/lib/python3.10/site-packages/torch/autograd/__init__.py:200](https://file+.vscode-resource.vscode-cdn.net/Users/suren/Desktop/Research/generative_models/pywph/examples/~/anaconda3/lib/python3.10/site-packages/torch/autograd/__init__.py:200), in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    195     retain_graph = create_graph
    197 # The reason we repeat same the comment below is that
    198 # some Python versions print out the first line of a multi-line function
...
--> 200 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    201     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    202     allow_unreachable=True, accumulate_grad=True)

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [CPUComplexFloatType [28, 256, 256]], which is output 0 of SubBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by bregaldo** [comment]
Hi, thanks for raising this issue!
We are currently working on this, and should solve this in the following days.
In the meantime, I would advise to get back to PyTorch v1.x (typically v1.13) if you want to use this package.

**Comment by sGourapura** [comment]
Hi again,
I am now attempting the run with PyTorch v1.13.0 with python 3.10.10 and still receiving the same error. Maybe a lower version of pytorch is required still? Or I am doing something wrong. I am doing this on conda, and simply uninstalled torch and reinstalled the older version following the conda website instructions for v1.13.0

**Comment by bregaldo** [comment]
OK, thanks for the update. Actually this code was tested and functional for PyTorch v1.10, but didn't know it would fail for v1.13.
We should fix this very soon..

**Comment by bregaldo** [comment]
OK we just fixed that. PyWPH is now compatible with PyTorch 1.13 & PyTorch 2.0. We also released v1.1.1 on pip, you will just have to run 'pip install pywph', and download the last version of the repo if you want to use the tutorial.
Let us know if everything works for you. Thanks!

**Comment by sGourapura** [comment]
Works great! Thank you!
